### ISSUE TITLE
Enforce linkage for items

### ISSUE THREAD

**Issue by sgallagher** [joeattardi/kolinahr#1]
Part of the intent of the Kellogg Logic Model is that items in each of the columns must always be linked to something in a column directly to its left (except Impacts, which are foundational).

It would be best if we could enforce that in the interface so that we can't have dangling entries (or at least have a verbose announcement that the model is incomplete).

**Comment by joeattardi** [comment]
Now you can't add a new item unless you have at least one outgoing link (except for Impacts, obviously).
