### ISSUE TITLE
Increase distinction between arrows

### ISSUE THREAD

**Issue by sgallagher** [joeattardi/kolinahr#15]
Right now, in larger models (e.g. [Fedora Server](http://kolinahr.herokuapp.com/edit/57d05a6984338834000515c9)), it can be very difficult to see where the arrows are pointing.

Some ideas to play with:
* Make the space between columns wider, to allow more space to differentiate
* Color the arrows in some fashion
 * Color them based on card color (or black, if the window is white)
  * A gradient going from the origin card color to the destination card color?
  * Solidly colored based on either the origin or destination color?

**Comment by joeattardi** [comment]
I made the space between the columns wider and added colors. Hopefully that will help.
