### ISSUE TITLE
Should substitute user's name when picture unavailable

### ISSUE THREAD

**Issue by sgallagher** [joeattardi/kolinahr#18]
Not all OpenID Connect services return an image for the user when logging in. If they do not, it would probably be nice to display their username rather than nothing in the upper-right except the logout button (which is unclear to be that, without the identity context next to it).

**Comment by joeattardi** [comment]
It should already show the name, see https://raw.githubusercontent.com/joeattardi/kolinahr/master/screenshot.png.

**Comment by sgallagher** [comment]
Screenshot indicating the missing name/logo. This is from the production environment I'm setting up at https://kolinahr.fedorainfracloud.org

If you have a FAS account, try logging in with it and see what happens. If you don't, you can register for free at http://admin.fedoraproject.org/accounts

![kolinahr - missing name](https://cloud.githubusercontent.com/assets/739555/19221118/c88ae88e-8e0a-11e6-825a-62c905d484fd.png)

**Comment by sgallagher** [comment]
With the latest git head, things look _better_, but still not quite right.

![kolinahr-missing-picture](https://cloud.githubusercontent.com/assets/739555/19348861/ff268d7e-911d-11e6-985b-d2efa65e9d30.png)

**Comment by joeattardi** [comment]
Ah, I forgot to make the placeholder profile image. I'll do that tonight.

**Comment by joeattardi** [comment]
Looks like this can be closed now.

**Comment by sgallagher** [comment]
Yeah, worked fine after I logged out and back in.
